### ISSUE TITLE
Add New User fails with autofill

### ISSUE THREAD

**Issue by peggylind** [DataAnalyticsinStudentHands/FormBuilder-Release#1]
Add a new user as owner to the form #312 failed.

Seems to be related to the typeahead module.
![screen shot 2016-01-29 at 8 32 52 am](https://cloud.githubusercontent.com/assets/6371988/12678633/59506dc6-c665-11e5-9adf-42d28b30b612.png)

**Comment by CarlSteven** [comment]
This is not a complete fix, but the best we can do according to - https://github.com/angular-ui/bootstrap/issues/5007
